services:
    postgresdb:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
      ports:
        - 5432:5432
      volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql


